apiVersion: 1
# list of datasources that should be deleted from the database
datasources:

  - name: Loki
    type: loki
    access: proxy 
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
